// $Id: 025_testUsedRequire_InvFailed_catched.main.kmt,v 1.2 2008-07-31 16:11:47 dvojtise Exp $
@mainClass "usedRequire::InvFailed_catched"
@mainOperation "main"


package usedRequire;


require kermeta
require "toBeRequired.kmt"
using kermeta::standard
using kermeta::exceptions
using kermeta::kunit

class InvFailed_catched inherits TestCase
{	

	operation main() : Void is do
    	var tr : TestRunner init TestRunner.new
		tr.run(InvFailed_catched)
		tr.printTestResult 
    end		


    operation test0() : Void is do 
        var m : MainToBeRequired init MainToBeRequired.new
        
        m.strRequired := "trucRequiredPre"
        m.b := false
        
        do
	        m.truc("trucRequiredPost") 
	        stdio.writeln("erreur!")
	        assert(false)
        rescue (err : ConstraintViolatedInv)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        	assert(true)
        end
        
        do
	        m.checkInvariants
	        assert(false)
        rescue (err : ConstraintViolatedInv)
        	stdio.writeln(err.toString)
        	stdio.writeln(err.message)
        	assert(true)
        end
        
    end
}