@mainClass "testPackageTestExceptions::TestExceptions"
@mainOperation "testmain_operation"

package testPackageTestExceptions;

require kermeta

using kermeta::standard
using kermeta::exceptions
 
 
class A
 {
  	operation opA1 (b : Boolean) is do
 		if (b) then
 			raise do var e : Exception init Exception.new
	 			e.message := "exceptionA"
 				e
 			end
 		else raise do var e : Exception init Exception.new
	 			e.message := "27"
 				e
 			end
 		end
 	end

 	operation opA2(b1 : Boolean,b2 : Boolean) is do
 		if b1 then do
 			opA1(b2)
 			rescue (s : Exception)
 			 stdio.write(s.message)
 			 stdio.writeln(" rescued")
 			 end
 		else do
 			opA1(b2)
 			rescue (i : Exception)
 			 stdio.write(i.message.toString)
 			 stdio.writeln(" propagated")
 			 //raise i
 			 end
 		end
 	end
 }
 
class B
{
 	operation opB(a : A,b1 : Boolean,b2 : Boolean) is do
 		if (b1) then do
 			a.opA1(b2)
 			rescue (s : Exception)
 			 stdio.write(s.message)
 			 stdio.writeln(" rescued")
 			 end
 		else do
 			a.opA1(b2)
 			rescue (i : Exception)
 			 stdio.write(i.message.toString)
 			 stdio.writeln(" propagated")
 			 //raise i
 			 end
 		end
 		rescue (s : Exception)
 			 stdio.write(s.message)
 			 stdio.writeln(" rescued")
 	end
}

class TestExceptions inherits kermeta::kunit::TestCase
{    
     operation testmain_operation() is do
     	var a : A
     	var b : B
     	
     	a := A.new
     	b := B.new
     	
     	do
     		a.opA1(true)
     		assert(false)
     		rescue (s:Exception)
     			assert(true)
     	end
     	do
     		a.opA1(false)
     		assert(false)
     		rescue (i:Exception)
     			assert(true)
     	end
     	a.opA2(true,true)
     	do
     		a.opA2(true,false)
     		assert(false)
     		rescue (i:Exception)
     			assert(true)
     	end
     	do
     		a.opA2(false,true)
     		assert(true)
     		rescue (s:String)
     			assert(true)
     	end
     	do
      		a.opA2(false,false)
      		assert(false)
      		rescue(i:Exception)
      			assert(true)
      	end
      	b.opB(a,true,true)
      	b.opB(a,false,true)
      	do
	      	b.opB(a,true,false)
	      	assert(false)
	      	rescue(i:Exception)
	      		assert(true)
	    end
     	do
	      	b.opB(a,false,false)
	      	assert(false)
	      	rescue(i:Exception)
	      		assert(true)
	    end
     end
     
}    
